author: Çağan Seyrek
github_profile: https://github.com/caganseyrek

site_link: https://caganseyrek.github.io

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - anchors.js

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM