author: Çağan Seyrek
github_profile: https://github.com/caganseyrek/

site_repo: https://github.com/caganseyrek/caganseyrek.github.io/
site_url: https://caganseyrek.github.io/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - mdstyle.md
  - paragraph.md
  - anchors.js

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "404"
    values:
      layout: "notfound"